name: epsa_ventas
description: "Aplicacion de soporte para el equipo de ventas de EPSA México"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  open_filex: ^4.7.0
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.4.3
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    # Datasheets
    - assets/pdfs/Datasheets/CHO/
    - assets/pdfs/Datasheets/CVT/
    - assets/pdfs/Datasheets/CYA/
    - assets/pdfs/Datasheets/DCL/
    - assets/pdfs/Datasheets/LCP/
    - assets/pdfs/Datasheets/MPE/
    - assets/pdfs/Datasheets/NBE/
    - assets/pdfs/Datasheets/NED/
    - assets/pdfs/Datasheets/PII/
    - assets/pdfs/Datasheets/RLW/
    - assets/pdfs/Datasheets/TWI/
    - assets/pdfs/Datasheets/VAC/
    - assets/pdfs/Datasheets/WMS/
    # Planos
    - assets/pdfs/Planos/CHO/Bag Handling Systems/
    - assets/pdfs/Planos/CHO/Open Mouth Bag Fillers/
    - assets/pdfs/Planos/CHO/Bulk Bag Filling Systems/
    - assets/pdfs/Planos/CHO/Bulk Bag Unloading Systems/
    - assets/pdfs/Planos/CVT/
    - assets/pdfs/Planos/NED/
    - assets/pdfs/Planos/CYA/
    - assets/pdfs/Planos/DCL/
    - assets/pdfs/Planos/LCP/
    - assets/pdfs/Planos/MPE/Molinos/
    - assets/pdfs/Planos/MPE/Chain Vey/
    - assets/pdfs/Planos/NBE/
    - assets/pdfs/Planos/PII/
    - assets/pdfs/Planos/PII/CLM/
    - assets/pdfs/Planos/PII/G Mill/
    - assets/pdfs/Planos/PII/Sifter/
    - assets/pdfs/Planos/PII/Mega Mill/
    - assets/pdfs/Planos/PII/Roto-Mill/
    - assets/pdfs/Planos/PII/Fine Grinder/
    - assets/pdfs/Planos/PII/Rotary Valve/
    - assets/pdfs/Planos/RLW/Floorscales/
    - assets/pdfs/Planos/RLW/Indicadores/
    - assets/pdfs/Planos/RLW/Bascula de ejes/
    - assets/pdfs/Planos/RLW/Celdas de carga/
    - assets/pdfs/Planos/RLW/Bascula de Camiones/
    - assets/pdfs/Planos/RLW/Bascula Ferrocarrilera/
    - assets/pdfs/Planos/TWI/Dosificadores/
    - assets/pdfs/Planos/TWI/Pesaje en banda/
    - assets/pdfs/Planos/TWI/Dosificadores de banda/
    - assets/pdfs/Planos/VAC/
    - assets/pdfs/Planos/WMS/HDX/
    - assets/pdfs/Planos/WMS/UDV/
    - assets/pdfs/Planos/WMS/KWIK KLEAN/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/favicon.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/branding/favicon.png
