// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZDzhlR3C5aszR_PGo-ts0-IFy64XUUf4',
    appId: '1:1095833155440:web:f672e147cfcc249bf181b5',
    messagingSenderId: '1095833155440',
    projectId: 'epsa-ventas',
    authDomain: 'epsa-ventas.firebaseapp.com',
    storageBucket: 'epsa-ventas.firebasestorage.app',
    measurementId: 'G-6MKHP6EPZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1dZp611Vq4YCVqum7ILwyktoLvyUZ8bk',
    appId: '1:1095833155440:android:32cb1453c55380eef181b5',
    messagingSenderId: '1095833155440',
    projectId: 'epsa-ventas',
    storageBucket: 'epsa-ventas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9MFyR2GS2lPgW1ETmjgTZ7Yu6FvzxQe8',
    appId: '1:1095833155440:ios:95d3b4bfafe6a23af181b5',
    messagingSenderId: '1095833155440',
    projectId: 'epsa-ventas',
    storageBucket: 'epsa-ventas.firebasestorage.app',
    iosBundleId: 'com.epsa.epsaVentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9MFyR2GS2lPgW1ETmjgTZ7Yu6FvzxQe8',
    appId: '1:1095833155440:ios:95d3b4bfafe6a23af181b5',
    messagingSenderId: '1095833155440',
    projectId: 'epsa-ventas',
    storageBucket: 'epsa-ventas.firebasestorage.app',
    iosBundleId: 'com.epsa.epsaVentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZDzhlR3C5aszR_PGo-ts0-IFy64XUUf4',
    appId: '1:1095833155440:web:40c988e21bf4ac45f181b5',
    messagingSenderId: '1095833155440',
    projectId: 'epsa-ventas',
    authDomain: 'epsa-ventas.firebaseapp.com',
    storageBucket: 'epsa-ventas.firebasestorage.app',
    measurementId: 'G-K76NXY9HJQ',
  );
}
